name: scrollable_positioned_list
version: 1.0.0
description: >
  A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/google/flutter.widgets/tree/master/packages/scrollable_positioned_list

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
